# Generated by Django 4.2.25 on 2025-10-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fitness_data',
            new_name='FitnessData',
        ),
    ]
