# Generated by Django 4.2.25 on 2025-10-24 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], max_length=20)),
                ('goal', models.CharField(choices=[('cardio', 'Improve cardio fitness'), ('strength', 'Improve strength'), ('balanced', 'Improve health (balanced)')], max_length=20)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
